name: support.statsig.com deployment

on:
  push:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-20.04
    #    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - run: git lfs pull
      - name: npm package cache
        uses: actions/cache@v2
        env:
          cache-name: npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: statsig/support:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Deploy to Latest Cluster
        uses: roim/kubectl-via-eksctl@main
        env:
          aws_access_key_id: ${{ secrets.LATEST_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.LATEST_AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          cluster: ${{ secrets.LATEST_CLUSTER_NAME }}
        with:
          args: rollout restart deployment/support
      - name: Validate Deployment
        uses: roim/kubectl-via-eksctl@main
        env:
          aws_access_key_id: ${{ secrets.LATEST_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.LATEST_AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          cluster: ${{ secrets.LATEST_CLUSTER_NAME }}
        with:
          args: rollout status deployment/support
